# Generated by Django 5.2.9 on 2026-02-10 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("firms", "0004_firminvitation_firmmember"),
        ("lawyers", "0003_alter_lawyer_address"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("lawyer", "Lawyer"), ("firm", "Firm")], max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("district", "District Court"),
                            ("high", "High Court"),
                            ("supreme", "Supreme Court"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("registered", "Registered"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("client_full_name", models.CharField(max_length=255)),
                ("client_address", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("client_phone", models.CharField(max_length=20)),
                ("client_date_of_birth", models.DateField()),
                ("client_citizenship_number", models.CharField(max_length=100)),
                ("client_gender", models.CharField(max_length=20)),
                ("waris_full_name", models.CharField(blank=True, max_length=255)),
                ("waris_email", models.EmailField(blank=True, max_length=254)),
                ("waris_address", models.CharField(blank=True, max_length=255)),
                ("waris_phone", models.CharField(blank=True, max_length=20)),
                ("waris_date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "waris_citizenship_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("waris_gender", models.CharField(blank=True, max_length=20)),
                (
                    "case_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="cases.casecategory",
                    ),
                ),
                (
                    "client_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_cases",
                        to="firms.firm",
                    ),
                ),
                (
                    "owner_lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solo_cases",
                        to="lawyers.lawyer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseDate",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_type",
                    models.CharField(
                        choices=[
                            ("tarik", "Tarik Date"),
                            ("pesi", "Pesi Date"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("remark", models.TextField(blank=True)),
                ("assigned_to_name", models.CharField(blank=True, max_length=255)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by_type",
                    models.CharField(
                        choices=[
                            ("lawyer", "Lawyer"),
                            ("firm", "Firm"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_documents",
                        to="media.image",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_case_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseLawyer",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead Lawyer"),
                            ("assistant", "Assistant Lawyer"),
                        ],
                        default="assistant",
                        max_length=20,
                    ),
                ),
                ("can_edit", models.BooleanField(default=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_lawyers",
                        to="cases.case",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_assignments",
                        to="lawyers.lawyer",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "lawyer")},
            },
        ),
    ]
