# Generated by Django 5.2.9 on 2026-02-10 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_casedate_casedocument_caselawyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="client_address",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_citizenship_number",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_date_of_birth",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_email",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_full_name",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_gender",
        ),
        migrations.RemoveField(
            model_name="case",
            name="client_phone",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_address",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_citizenship_number",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_date_of_birth",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_email",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_full_name",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_gender",
        ),
        migrations.RemoveField(
            model_name="case",
            name="waris_phone",
        ),
        migrations.CreateModel(
            name="CaseClient",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("citizenship_number", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseWaris",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("citizenship_number", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=20)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waris",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
