# Generated by Django 5.2.9 on 2026-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_remove_case_client_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="document_scope",
            field=models.CharField(
                choices=[("internal", "Internal / My File"), ("client", "Client File")],
                default="internal",
                max_length=20,
            ),
        ),
    ]
