# Generated by Django 5.2.9 on 2026-02-11 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_casedocument_document_scope"),
        ("clients", "0002_alter_client_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="client_user",
        ),
        migrations.AddField(
            model_name="case",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="clients.client",
            ),
        ),
        migrations.CreateModel(
            name="CaseClientDetails",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("citizenship_number", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_details",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="CaseClient",
        ),
    ]
