# Generated by Django 5.2.9 on 2026-01-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("firms", "0002_alter_firm_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm",
                to="addresses.address",
            ),
        ),
    ]
