# Generated by Django 5.2.9 on 2026-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0001_initial"),
        ("firms", "0002_alter_firmverification_firm_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmverification",
            name="firm_email",
        ),
        migrations.RemoveField(
            model_name="firmverification",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="firm",
            name="services",
            field=models.ManyToManyField(related_name="firms", to="case.casecategory"),
        ),
    ]
