# Generated by Django 5.2.9 on 2026-01-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idverification",
            name="passport_size_photo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passport_size_photo",
                to="media.image",
            ),
        ),
        migrations.AlterField(
            model_name="idverification",
            name="photo_back",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_id_back",
                to="media.image",
            ),
        ),
        migrations.AlterField(
            model_name="idverification",
            name="photo_front",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_id_front",
                to="media.image",
            ),
        ),
    ]
