# Generated by Django 5.2.9 on 2026-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_idverification_passport_size_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idverification",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_ID", "National ID"),
                    ("CITIZENSHIP", "Citizenship"),
                ],
                max_length=30,
            ),
        ),
    ]
