# Generated by Django 5.2.9 on 2025-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
