# Generated by Django 5.2.9 on 2026-01-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="is_email_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("lawyer", "Lawyer"),
                    ("firm", "Firm Admin"),
                    ("admin", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
