# Generated by Django 5.2.9 on 2026-02-09 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQueryHistory",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("lookup", "Lookup"),
                            ("interpretation", "Interpretation"),
                            ("case_based", "Case Based"),
                            ("predictive", "Predictive"),
                            ("general", "General"),
                            ("not_legal", "Not Legal"),
                            ("lawyer_recommendation", "Lawyer Recommendation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("response", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
