# Generated by Django 5.2.9 on 2026-02-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        ("cases", "0001_initial"),
        ("firms", "0004_firminvitation_firmmember"),
        ("lawyers", "0003_alter_lawyer_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiqueryhistory",
            name="response",
        ),
        migrations.AddField(
            model_name="aiqueryhistory",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiqueryhistory",
            name="case_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_queries",
                to="cases.casecategory",
            ),
        ),
        migrations.AddField(
            model_name="aiqueryhistory",
            name="raw_ai_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiqueryhistory",
            name="recommended_firms",
            field=models.ManyToManyField(
                blank=True, related_name="ai_recommendations", to="firms.firm"
            ),
        ),
        migrations.AddField(
            model_name="aiqueryhistory",
            name="recommended_lawyers",
            field=models.ManyToManyField(
                blank=True, related_name="ai_recommendations", to="lawyers.lawyer"
            ),
        ),
    ]
