# Generated by Django 5.2.9 on 2026-02-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_assistant",
            "0002_remove_aiqueryhistory_response_aiqueryhistory_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiqueryhistory",
            name="query_type",
            field=models.CharField(
                choices=[
                    ("lookup", "Lookup"),
                    ("interpretation", "Interpretation"),
                    ("case_based", "Case Based"),
                    ("predictive", "Predictive"),
                    ("general", "General"),
                    ("not_legal", "Not Legal"),
                    ("recommendation", "Recommendation"),
                ],
                max_length=30,
            ),
        ),
    ]
