# Generated by Django 5.2.9 on 2026-01-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("lawyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lawyer",
                to="addresses.address",
            ),
        ),
    ]
