# Generated by Django 5.2.9 on 2026-01-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barverification",
            name="license_photo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lawyer_license",
                to="media.image",
            ),
        ),
    ]
