# Generated by Django 5.2.9 on 2026-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0001_initial"),
        ("lawyers", "0002_alter_barverification_license_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyer",
            name="services",
            field=models.ManyToManyField(
                related_name="lawyers", to="case.casecategory"
            ),
        ),
    ]
