# Generated by Django 5.2.9 on 2026-02-13 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking Created"),
                            ("booking_accepted", "Booking Accepted"),
                            ("booking_rejected", "Booking Rejected"),
                            ("firm_invitation_received", "Firm Invitation Received"),
                            ("firm_invitation_accepted", "Firm Invitation Accepted"),
                            ("firm_invitation_rejected", "Firm Invitation Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notificatio_recipie_1dd18d_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                ],
            },
        ),
    ]
